name: Deploy Frontend to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Debug folders (IMPORTANT)
        run: ls -R

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd vivam_profile3-main/frontend
          npm install

      - name: Build project
        run: |
          cd vivam_profile3-main/frontend
          npm run build

      - name: Check build
        run: |
          ls -la vivam_profile3-main/frontend/build
      - name: Debug folders
        run: ls -R

      - name: Install AWS CLI
        run: sudo apt-get install awscli -y

      - name: Deploy to S3
        run: |
          aws s3 sync vivam_profile3-main/frontend/build s3://$S3_BUCKET --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
